#include "functions.h"
#include "functions.C"

#include "TF1.h"
#include "TH1F.h"
#include "TH1I.h"
#include "TH2F.h"
#include "TTree.h"
#include "TClonesArray.h"
#include "TBranch.h"
#include "TChain.h"
#include "TTree.h"
#include "TFile.h"
#include "TLegend.h"
#include "TStyle.h"
#include "TString.h"
#include "TBits.h"
#include "TMath.h"
#include "TSystem.h"
#include "TRandom2.h"
#include "TMVA/Reader.h"
#include "TMVA/Tools.h"
#include <TLorentzVector.h>

TFile *myFile;// = new TFile("theMiniTree.root","RECREATE");
TTree *myTree_;
TChain *chain = new TChain("photons");
//TMVA::Reader* reader;
  bool doMC, doNN, doAllHlt, doHLTobject, doSmearing;
  int NbEntries;

// MiniTtree d'entr�e
                int pho_iEvent;
                int pho_EventNumber;
                int pho_RunNumber;
		int pho_lumiSection;
                int pho_isEB;
                int pho_isEE;
                int pho_isEEP;
                int pho_isEEM;
                int pho_isAlsoElectron;
                int pho_ElectronClassification;
                int pho_hasPixelSeed;
                float pho_et;
                float pho_energy;
                float pho_px;
                float pho_py;
                float pho_pz;
                float pho_eta;
                float pho_phi;
                float pho_s4;
                float pho_s9;
                float pho_eMax;
                float pho_e2nd;
                float pho_r19;
                float pho_r9;
		float pho_r9old;
                float pho_S9overS9minusS1S2;
                float pho_cEE;
                float pho_cEP;
                float pho_cPP;
                float pho_phiwidth;
                float pho_etawidth;
                float pho_sigmaphi;
                float pho_sigmaeta;
                float pho_sigmaIetaIeta;
                float pho_sigmaEtaEta;
                float pho_hoe;
                float pho_IsoEcalRechit;
                float pho_IsoHcalRechit;
                float pho_IsoSolidTrkCone;
                float pho_IsoHollowTrkCone;
                float pho_IsoEcalRechit03;
                float pho_IsoHcalRechit03;
                float pho_IsoSolidTrkCone03;
                float pho_IsoHollowTrkCone03;
		int   pho_IsoSolidNtrackCone;
		int   pho_IsoHollowNtrackCone;
		float pho_IsoSolidTrkConeWorst;
                float pho_esRatio;
                int pho_convNTracks;
                float pho_ptoverjetpt;
                float pho_DrSCclosest;
                float pho_DrTrkclosest;
		float pho_transverseToJetRatio;
                float pho_ptoverjetpt_pt2;
                float pho_DrTrkclosest_pt2;
                float pho_ptoverjetpt_pt5;
                float pho_DrTrkclosest_pt5;
                float pho_ptoverjetpt_pt10;
                float pho_DrTrkclosest_pt10;
                float pho_ptoverjetpt_pt15;
                float pho_ptoverjetpt_PFlow;
                float pho_ptoverjetpt_PFlow_pt2;
                float pho_ptoverjetpt_PFlow_pt5;
                float pho_ptoverjetpt_PFlow_pt10;
                float pho_ptoverjetpt_sisCone;
                float pho_ptoverjetpt_sisCone_pt2;
                float pho_ptoverjetpt_sisCone_pt5;
                float pho_ptoverjetpt_sisCone_pt10;
                int pho_isAfterCut1;
                int pho_isAfterCut2;
                int pho_isAfterCut3;
                int pho_isAfterCut4;
                int pho_isAfterCut5;
                int pho_isAfterCut6;
                int pho_isAfterCut7;
                int pho_isAfterCut8;
                float pho_jetEMfraction;
                float pho_DrJetClosest;
                int pho_isLoose;
                int pho_isTight;
                int pho_isEBGap;
                int pho_isEEGap;
                int pho_GenId;
                int pho_MotherId;
                int pho_isPromptGenPho;
                int pho_isFromQuarkGen;
                int pho_isPi0Gen;
                int pho_isEtaGen;
                int pho_isRhoGen;
                int pho_isOmegaGen;
                int pho_isGenElectron;
                int pho_eventPassHLT_Photon10_L1R;
                int pho_eventPassHLT_Photon15_L1R;
                int pho_eventPassHLT_DoublePhoton10_L1R;
                float pho_eventPtHat;
		int pho_eventProcessId;
                int pho_nVertex;
		int pho_nGenVertex;
		int pho_nGenOOTVertex;
		float pho_rho;
                float pho_PromptGenIsoEnergyStatus1_cone02;
                float pho_PromptGenIsoEnergyStatus2_cone02;
                float pho_PromptGenIsoEnergyStatus1_cone03;
                float pho_PromptGenIsoEnergyStatus2_cone03;
                float pho_PromptGenIsoEnergyStatus1_cone035;
                float pho_PromptGenIsoEnergyStatus2_cone035;
                float pho_PromptGenIsoEnergyStatus1_cone04;
                float pho_PromptGenIsoEnergyStatus2_cone04;
                int pho_seedSeverity;
                int pho_recoFlag;
		int isAspike;
		int pho_HLT_bit0;
		int pho_HLT_bit1;
		int pho_HLT_bit2;
		int pho_HLT_bit3;
		int pho_HLT_bit4;
		int pho_HLT_bit5;
		int pho_HLT_bit6;
		int pho_HLT_bit7;
		int pho_HLT_bit8;
		int pho_HLT_bit9;
		int pho_HLT_bit10;
		int pho_HLT_bit11;
		int pho_HLT_bit12;
		int pho_HLT_bit13;
		int pho_HLT_bit14;
		int pho_HLT_bit15;
		int pho_HLT_bit16;
		int pho_HLT_bit17;
		int pho_HLT_bit18;
		int pho_HLT_bit19;
		int pho_HLT_bit20;
		int pho_HLT_bit21;
		int pho_HLT_bit22;
		int pho_HLT_bit23;
		int pho_HLT_bit24;
		int pho_HLT_bit25;
		int pho_HLT_bit26;
		int pho_HLT_bit27;
		int pho_HLT_bit28;
		int pho_HLT_bit29;
		int pho_HLT_bit30;
		int pho_HLT_bit31;
		int pho_HLT_bit32;
		int pho_HLT_bit33;
		int pho_HLT_bit34;
		int pho_HLT_bit35;
		int pho_HLT_bit36;
		int pho_HLT_bit37;
		int pho_HLT_bit38;
		int pho_HLT_bit39;
		int pho_HLT_bit40;
		int pho_HLT_bit41;
		int pho_HLT_bit42;
		int pho_HLT_bit43;
		int pho_HLT_bit44;
		int pho_HLT_bit45;
                // sc infos
                float pho_SCeta;
                float pho_SCphi;
                float pho_SCEtraw;
                float pho_SCEt;
                float pho_SCr9;
                float pho_SCbr;
                int   pho_SCnbBC;
                int   pho_SCnXtal;
                // theNN
		float pho_NNshapeOutput;
		float pho_NNenvOutput;
		float pho_NNcombOutput;
	float pho_trueE;
	float pho_truePx;
	float pho_truePy;
	float pho_truePz;
	float pho_trueEta;
	float pho_truePhi;
	int pho_isMatchingWithHLTObject;
	///new CL vars
	float pho_SCEraw;
	float pho_e2x2;
	float pho_e5x5;
	float pho_secondMomentMaj;
	float pho_secondMomentMin;
	float pho_secondMomentAlpha;
	//calculated for now
	float pho_lambdaRatio;
	float pho_ratioSeed;
	float pho_ratioS4;
	float pho_lamdbaDivCov;
	float pho_CovAngle;
	int pho_isMatchWithMuon;
        int pho_isConverted;
	int pho_isPassingCIC;

	int pho_Cat;
	float pho_CICcombIso;
	float pho_CICworstComb;
	float pho_CICtrackIso;
	float pho_CICdR;
	int pho_isPassingCICRho;
	float pho_CICcombIsoRho;
	float pho_CICworstCombRho;
	float pho_etWorstVertex;



// miniTree de sortie

int event_number;    
int event_realNumber;
int event_runNumber;                                    
int event_LumiSection; 
int event_weightLO;                                       
int event_weightNLO;                                     
float event_eventPtHat; 
int event_processId;
int event_nVertex;
int event_nGenVertex;
int event_nGenOOTVertex;
int event_nPhotons;
float  event_rho;
int dipho_cat4;                                           
int dipho_cat4bis;                                        
int dipho_cat6;                                           
int dipho_cat12;                                          
float dipho_mgg;                                
float dipho_qt;                                           
float dipho_ql;                                           
float dipho_deltaR;                                       
float dipho_costhetastar;                                 
float dipho_eta;      
float dipho_mggTrue;
float dipho_qtTrue;
float dipho_deltaphiTrue;
float dipho_costhetastarTrue;
float dipho_etastar;                                      
float dipho_rapidity;                                     
float dipho_deltaphi;                                     
float dipho_costhetastar_parton;                          
float dipho_tanhrapiditydiff;                             
float pholead_pt;                                         
float photrail_pt;                                        
float pho1_pt;                                            
float pho2_pt;                                            
float pholead_eta;                                        
float photrail_eta;                                       
float pholead_r9;                                         
float photrail_r9;                                        
float pholead_cPP;                                        
float photrail_cPP;                                        
float pholead_cEE;                                      
float photrail_cEE;                                      
float pholead_cEP;
float photrail_cEP;
float pholead_r19;
float photrail_r19;
float pholead_ratioSeed; 
float photrail_ratioSeed;
float pholead_ratioS4; 
float photrail_ratioS4;
float pholead_lambdaRatio; 
float photrail_lambdaRatio;
float pholead_lamdbaDivCov; 
float photrail_lamdbaDivCov; 
float pholead_lambdaRatioRand; 
float photrail_lambdaRatioRand;
float pholead_lamdbaDivCovRand; 
float photrail_lamdbaDivCovRand; 
float pholead_sigmaphi;                                   
float photrail_sigmaphi;                                  
float pholead_secondMomentMaj;
float photrail_secondMomentMaj;
float pholead_secondMomentMin;
float photrail_secondMomentMin;
float pholead_secondMomentAlpha;
float photrail_secondMomentAlpha;
float pholead_covAngle;
float photrail_covAngle;
float pholead_covAngle2;
float photrail_covAngle2;
float pholead_covAngleRand;
float photrail_covAngleRand;
float pholead_covAngle2Rand;
float photrail_covAngle2Rand;
float pholead_S9overS9minusS1S2;                          
float photrail_S9overS9minusS1S2;                         
float pholead_etawidth;                                   
float photrail_etawidth;                                  
float pholead_sigieta;                                    
float photrail_sigieta;                                   
float pholead_ptoverjetpt;                                
float photrail_ptoverjetpt;                               
float pholead_DrScClosest;                                
float photrail_DrScClosest;                               
float pholead_DrTrkClosest;                               
float photrail_DrTrkClosest;                             
float pholead_transverseToJetRatio;
float photrail_transverseToJetRatio; 
float pholead_MLPoutputClusterShape;                      
float photrail_MLPoutputClusterShape;                     
float pholead_MLPoutputEnv;                               
float photrail_MLPoutputEnv;                              
float pholead_MLPoutputClusterShapeEnv;                   
float photrail_MLPoutputClusterShapeEnv;                  
float phoNNmin_MLPoutputClusterShape;                     
float phoNNmax_MLPoutputClusterShape;                     
float phoNNmin_MLPoutputEnv;                              
float phoNNmax_MLPoutputEnv;                              
float phoNNmin_MLPoutputClusterShapeEnv;                  
float phoNNmax_MLPoutputClusterShapeEnv;                  
float pholead_MLPoutputNNisol;                            
float photrail_MLPoutputNNisol;                           
float pho1_MLPoutputNNisol;                               
float pho2_MLPoutputNNisol;                               
float phoNNmin_MLPoutputNNisol;                           
float phoNNmax_MLPoutputNNisol;
float pholead_HcalIso;
float photrail_HcalIso;
float pholead_EcalIso;
float photrail_EcalIso;
float pholead_TrackerIso;
float photrail_TrackerIso;
float pholead_HcalIsodR03;
float photrail_HcalIsodR03;
float pholead_EcalIsodR03;
float photrail_EcalIsodR03;
float pholead_TrackerIsodR03;
float photrail_TrackerIsodR03;
float pholead_HcalIsoPerso;
float photrail_HcalIsoPerso;
float pholead_EcalIsoPerso;
float photrail_EcalIsoPerso;
float pholead_TrackerIsoPerso;
float photrail_TrackerIsoPerso;
float pholead_IsoSolidTrkConeWorst;
float photrail_IsoSolidTrkConeWorst;
int   pholead_TrackerIsoN;
int   photrail_TrackerIsoN;
int   pholead_TrackerIsoNsolid;
int   photrail_TrackerIsoNsolid;
float pholead_hoe;
float photrail_hoe;
float pholead_DrJetClosest;
float photrail_DrJetClosest;
float pholead_jetEMfraction;
float photrail_jetEMfraction;
int pholead_isPromptGenPho;
int photrail_isPromptGenPho;
int pholead_isFromQuarkGen;
int photrail_isFromQuarkGen;
int pholead_HasPixSeed;
int photrail_HasPixSeed;
int pholead_seedSeverity;
int photrail_seedSeverity;
int pholead_recoFlag;
int photrail_recoFlag;
int pholead_isEB;
int photrail_isEB;
int pholead_isEE;
int photrail_isEE;
float pholead_NNshapeOutput;
float photrail_NNenvOutput;
float pholead_NNenvOutput;
float photrail_NNshapeOutput;
float pholead_NNcombOutput;
float photrail_NNcombOutput;
float dipho_minNNshape;
float dipho_minNNcomb;
float dipho_minNNenv;
int   dipho_placeCats;
float dipho_minIsoTrack;
float dipho_maxIsoTrack;
float pholead_etaSC;
float photrail_etaSC;
float pholead_SCbr;
float photrail_SCbr;
int pholead_isMin;
int  photrail_isMin;
int dipho_HLT_bit0;
int dipho_HLT_bit1;
int dipho_HLT_bit2;
int dipho_HLT_bit3;
int dipho_HLT_bit4;
int dipho_HLT_bit5;
int dipho_HLT_bit6;
int dipho_HLT_bit7;
int dipho_HLT_bit8;
int dipho_HLT_bit9;
int dipho_HLT_bit10;
int dipho_HLT_bit11;
int dipho_HLT_bit12;
int dipho_HLT_bit13;
int dipho_HLT_bit14;
int dipho_HLT_bit15;
int dipho_HLT_bit16;
int dipho_HLT_bit17;
int dipho_HLT_bit18;
int dipho_HLT_bit19;
int dipho_HLT_bit20;
int dipho_HLT_bit21;
int dipho_HLT_bit22;
int dipho_HLT_bit23;
int dipho_HLT_bit24;
int dipho_HLT_bit25;
int dipho_HLT_bit26;
int dipho_HLT_bit27;
int dipho_HLT_bit28;
int dipho_HLT_bit29;
int dipho_HLT_bit30;
int dipho_HLT_bit31;
int dipho_HLT_bit32;
int dipho_HLT_bit33;
int dipho_HLT_bit34;
int dipho_HLT_bit35;
int dipho_HLT_bit36;
int dipho_HLT_bit37;
int dipho_HLT_bit38;
int dipho_HLT_bit39;
int dipho_HLT_bit40;
int dipho_HLT_bit41;
int dipho_HLT_bit42;
int dipho_HLT_bit43;
int dipho_HLT_bit44;
int dipho_HLT_bit45;
float dipho_Kfactor;
float pholead_trueE;
float pholead_truePx;
float pholead_truePy;
float pholead_truePz;
float pholead_trueEta;
float pholead_truePhi;
float photrail_trueE;
float photrail_truePx;
float photrail_truePy;
float photrail_truePz;
float photrail_trueEta;
float photrail_truePhi;
int   pholead_isMatchingWithHLTObject;
int   photrail_isMatchingWithHLTObject;
float dipho_minR9;
float dipho_maxR9;
float dipho_maxHoE;
float dipho_maxIsoEcal;
float dipho_maxIsoHcal;
float dipho_maxIsoTracks;
float dipho_maxSigIeta;
float dipho_R9bestNN;
float dipho_R9worstNN;
float pholead_s4;
float pholead_s9;
float pholead_e2x2;
float pholead_e5x5;
float pholead_SCEraw;
float photrail_s4;
float photrail_s9;
float photrail_e2x2;
float photrail_e5x5;
float photrail_SCEraw;
float pholead_eMax;
float photrail_eMax;
int   pholead_isMatchWithMuon;
int   photrail_isMatchWithMuon;
int   pholead_SCnbBC;
int   photrail_SCnbBC;
int   pholead_SCnXtal;
int   photrail_SCnXtal;
int   pholead_isConverted;
int   photrail_isConverted;
int   pholead_isPassingCIC;
int   photrail_isPassingCIC;
int pholead_Cat;
int photrail_Cat;
float pholead_CICcombIso;
float photrail_CICcombIso;
float pholead_CICworstComb;
float photrail_CICworstComb;
float pholead_CICtrackIso;
float photrail_CICtrackIso;
float pholead_CICdR;
float photrail_CICdR;
int pholead_isPassingCICRho;
int photrail_isPassingCICRho;
float pholead_CICcombIsoRho;
float photrail_CICcombIsoRho;
float pholead_CICworstCombRho;
float photrail_CICworstCombRho;
float pholead_etWorstVertex;
float photrail_etWorstVertex;

  TLorentzVector P_loc[100] ;
TLorentzVector Ptrue_loc[100];
  double Eta_loc[100] ;
  double R9_loc[100] ;
  double cPP_loc[100] ;
  double cEE_loc[100] ;
  double EtaWidth_loc[100] ;
  double SigIeta_loc[100] ;
  double sigmaphi_loc[100] ;
  double S9overS9minusS1S2_loc[100] ;
  double ptoverjetpt_loc[100] ;
  double closestSC_dR_loc[100] ;
  double dR_SCtrkclosest_loc[100] ;

  double MLPoutputClusterShape_loc[100] ;
  double MLPoutputEnv_loc[100] ;
  double MLPoutputClusterShapeEnv_loc[100] ;
  double MLPoutputNNisol_loc[100] ;

  double TrackerIso_loc[100] ;
  double EcalIso_loc[100] ;
  double HcalIso_loc[100] ;
  double TrackerIsodR03_loc[100] ;
  double EcalIsodR03_loc[100] ;
  double HcalIsodR03_loc[100] ;
  double TrackerIsoPerso_loc[100] ;
  double EcalIsoPerso_loc[100] ;
  double HcalIsoPerso_loc[100] ;
  double HoE_loc[100] ;
  int HasPixSeed_loc[100] ;
  int SeedSeverity_loc[100] ;
  int RecoFlag_loc[100] ;
  
  float NNshapeOutput_loc[100];
  float NNenvOutput_loc[100];
  float NNcombOutput_loc[100];

  float etaSC_loc[100];
  float SCbr_loc[100]; 

  double DrJetClosest_loc[100] ;
  double JetEMfraction_loc[100] ;

  int isPromptGenPho_loc[100] ;
  int isFromQuarkGen_loc[100] ;

  int passHLT_Photon10_loc[100] ;
  int passHLT_Photon15_loc[100] ;
  int passHLT_DoublePhoton10_loc[100] ;

  int pho_HLT30_loc[100] ;
  int pho_HLT50_loc[100] ;
  int pho_HLTdiPho15_loc[100] ;
  int pho_HLTdiPho20_loc[100] ;

  double Kfactor_loc[100] ;

  float pho_sigmaIetaIeta_loc[100];
  int pho_isEB_loc[100];
  int pho_isEE_loc[100];

  float transverseToJetRatio_loc[100];
float pho_trueE_loc[100];
float pho_truePx_loc[100];
float pho_truePy_loc[100];
float pho_truePz_loc[100];
float pho_trueEta_loc[100];
float pho_truePhi_loc[100];
int   pho_isMatchingWithHLTObject_loc[100];
int pho_IsoSolidNtrackCone_loc[100];
int pho_IsoHollowNtrackCone_loc[100];
float pho_cEP_loc[100];
float pho_r19_loc[100];
float pho_ratioSeed_loc[100];
float pho_ratioS4_loc[100];
float pho_lambdaRatio_loc[100];
float pho_lamdbaDivCov_loc[100];

	float pho_secondMomentMaj_loc[100];
	float pho_secondMomentMin_loc[100];
	float pho_secondMomentAlpha_loc[100];
	float pho_CovAngle_loc[100];
	float pho_CovAngle2_loc[100];
float pho_s4_loc[100];
float pho_s9_loc[100];
float pho_e2x2_loc[100];
float pho_e5x5_loc[100];
float pho_SCEraw_loc[100];
float pho_eMax_loc[100];
int   pho_isMatchWithMuon_loc[100];

int pho_SCnbBC_loc[100];
int pho_SCnXtal_loc[100];
int pho_isConverted_loc[100];

float pho_IsoSolidTrkConeWorst_loc[100];
int pho_isPassingCIC_loc[100];

int pho_Cat_loc[100];
float pho_CICcombIso_loc[100];
float pho_CICworstComb_loc[100];
float pho_CICtrackIso_loc[100];
float pho_CICdR_loc[100];
int pho_isPassingCICRho_loc[100];
float pho_CICcombIsoRho_loc[100];
float pho_CICworstCombRho_loc[100];
float pho_etWorstVertex_loc[100];
